version: '2'

services:
  db:
    build: ./database
    # command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    networks:
      new:
        aliases:
          - database 
  web:
    build: .
    links:
      - db
    # volumes:
    #   - ./dist:/server/dist
    # command: cat package.json
    command: npm run debug 
    ports:
      - '3000:3000'
    networks:
      - new
    depends_on:
      - db

networks: 
  new:
